### PR TITLE
Added code/menus.mdx

### LINKED ISSUE #55: Add live code exercises: code/menus.mdx
## What's the problem?
The tutorial's underlying framework, [exerslide](https://github.com/facebookarchive/exerslide), was archived by its owner and has not been updated for several years. We want to modernize by migrating the tutorial to [docusaurus](https://github.com/facebook/docusaurus/)

## How can you help?
Recreate the live code exercises for the [Menus section](https://teachaccess.github.io/tutorial/#/10)

## How to do it?
Please see this [step-by-step guide](https://github.com/teachaccess/tutorial/blob/docusaurus/migration-instructions.md) for how to complete this task

Check out the Headings slide for an example ([before](https://github.com/teachaccess/tutorial/blob/master/slides/02-Developers/01-headings.html.md) and [after](https://github.com/teachaccess/tutorial/blob/docusaurus/docs/code/headings.mdx))

## Helpful links
- [Tutorial website](https://teachaccess.github.io/tutorial/#/10)
- [Exerslide file (old)](https://github.com/teachaccess/tutorial/blob/master/slides/02-Developers/08-menu.html.md)
- [Docusaurus file (new)](https://github.com/teachaccess/tutorial/blob/docusaurus/docs/code/menus.mdx)

### PR DESCRIPTION
**Pull request by amkonstant**
Fixes #55

My implementation is using a helper file `MenuExample` that is exporting functions for menu interaction. It is imported as `MenuHelpers` in [`ReactLiveScope`](https://docusaurus.io/docs/markdown-features/code-blocks#imports). This allows us to display only the relevant code to the reader: 

Screenshot 2021-10-29 at 23 44 33
.

### CODE REVIEW

**Comment by amkonstant** [comment]
I've forgot to replace the placeholder [Wrench Icon] with an actual icon. I'm working on it, sorry! Got too exited when the `ReactLiveScope` worked 😄

**Comment by amkonstant** [comment]
I've added the correct `kbd` tag and the **wrench** icon. Initially I wanted to add _FontAwesome_ icons, but decided against it and used an emoji instead. I couldn't figure out how to use only one icon and how to align it properly using Markdown, so I hope that this solution is OK at this stage 👌

**Comment by rachelruderman** [comment]
@amkonstant Thank you so much for your work on this!!!! It was definitely a complicated one!

I noticed your screenshot looks a-okay, but when I run this locally I see an error:

Screen Shot 2021-10-30 at 11 22 30 AM

Since Hacktoberfest is coming to a close and your PR gets us 90% of the way there, I'm happy to merge this as is! I'll leave it open until tomorrow in case you want to make changes. Either way, thank you so much! You did a great job 😺

**Comment by amkonstant** [comment]
@rachelruderman Thank you very much! I'll do my best to resolve the issue :)

**Comment by 7mary4** [comment]
Thank you @amkonstant for your contribution.

**Pull request merged**
