### PR TITLE
Added tables exercises

### PR DESCRIPTION
**Pull request by hannahkim21**
Hi! A few questions I had, I'm committing this to show progress. 

1. The original Tables page had custom CSS. Should I also customize the CSS? Would an inline way be preferred, or a separate file? The exerslide version had it inline, but I didn't see that in the docusaurus documentation. I think this would be for aesthetic reasons, as the ScreenReader is working. However, I don't think the "Editor Output" heading shows unless I put it in manually, I think that was a feature of the codeblocks in exerslide. 
2.  Are the exercise verifications functioning correctly?

Thank you!

### CODE REVIEW

**Comment by hannahkim21** [comment]
Hi @rachelruderman, thank you for the help and fixes! I added the suggestions, but haven't been able to get the customTheme.css to work. It's strange because it works separately [img attached]. 
My apologies for that! I don't think I'll finish in time, but I will keep looking. 

image

**Comment by rachelruderman** [comment]
Hi @hannahkim21 !! I just pulled your branch, reverted the commit `Rolling back .css changes` and it's working for me! I see your CSS changes to the table:
Screen Shot 2021-10-30 at 11 02 05 AM

Confirmed the exercise worked for me

Hacktoberfest is coming to a close so I'm happy to merge this PR if you revert the "Rolling back .css changes" commit :) Throwing a label `hacktoberfest-accepted` on just in case you don't see this in time

**Comment by 7mary4** [comment]
This is a great addition. I have updated content and will create an issue after this is merged to provide more accurate information.

**Comment by 7mary4** [comment]
For instance, the comment about chrome is no longer relevant. But don't make changes to the content, your contribution is fantastic for establishing the page.

**Comment by hannahkim21** [comment]
Thank you both for that information! I have reverted the last commit. I appreciate your guidance. Happy halloween! 🎃

**Review by rachelruderman — APPROVED** [review]

**Pull request merged**
